# Meta Data for SEO

## Homepage
title = "Maelstrom"
titleSeparator = "-"
titleAddition = ""
description = "Maelstrom is a HTTP reverse proxy that starts and stops containers on demand"

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "henkverlinde"
twitterCreator = "henkverlinde"
facebookAuthor = "verlinde.henk"
facebookPublisher = "verlinde.henk"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
#schemaTwitter = "https://twitter.com/henkverlinde"
#schemaLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaGitHub = "https://github.com/maelstromapp/maelstrom"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Maelstrom? <a class=\"alert-link\" href=\"https://github.com/maelstromapp/maelstrom/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/maelstromapp/maelstrom"
editPage = false
